# -*- coding: utf-8 -*-
"""bootstrap_para_media.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wcxXcAulhC_DX_lzFGcBDAgSyOtD9nxp
"""

import numpy as np
import matplotlib.pyplot as plt

np.random.seed(123)
poblacion = np.random.randint(0,500 , size=1000)
muestra = np.random.choice(poblacion, size=300) #n=300

muestra_media = []
for _ in range(10000):  #B=10000
    muestra_n = np.random.choice(muestra, size=300)
    muestra_media.append(muestra_n.mean())

plt.hist(muestra_media)

"""Comparamos las medias


"""

np.mean(muestra_media)

poblacion.mean()

muestra.mean()