# -*- coding: utf-8 -*-
"""Ej3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BemQM3UzkNPzNpRts9yb0uo04HFTrtfn
"""

import pandas as pd, matplotlib.pyplot as plt, numpy as np, geopandas as gpd, contextily as ctx, seaborn as sns, os

"""Trato de comparar votos presidenciales por promedio de edades por comuna

Gráfico con promedio de edades por comuna (mayores a 16)
"""

sns.set(style = 'darkgrid')
df = pd.read_csv("/content/promedio_edad_comuna_16_para_arriba.csv")
eje_x = df["NOMBRE_REGION"]
eje_y = df["P03"]
plt.bar(eje_x, eje_y, color="lightcoral")
plt.xticks(rotation=90)
plt.ylabel("Promedio de edad")
plt.title('Promedio de edad por comuna')
plt.ylim(40,48)
plt.show()



sns.set(style = 'darkgrid')
df = pd.read_csv("/content/prom_std_edad_circuito.csv")
fig2=sns.catplot(data=df, x="NOMBRE_REGION", y="P03", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.NOMBRE_REGION, rotation=90)
plt.ylabel("Promedio de edad")
plt.title('Promedio de edad por comuna')
plt.ylim(40,48)
plt.show()

df =  pd.read_csv('/content/prom_std_edad_circuito.csv)
labels = df["NOMBRE_REGION"]
fit = df["P03"]
fdt = df["VOTOS_FDT_DIPNAC"]

x = np.arange(len(labels))  # the label locations
width = 0.35  # the width of the bars

fig, ax = plt.subplots()
rects1 = ax.bar(x - width/2, fit, width, label='FIT')
rects2 = ax.bar(x + width/2, fdt, width, label='FDT')


ax.set_ylabel('Votos')
ax.set_title('Comparación votos a diputados de FDT y FIT por comuna')
ax.set_xticks(x)
ax.set_xticklabels(labels)
ax.legend()

plt.xticks(rotation=90)

fig.tight_layout()

plt.show()

"""Promedio de edad por circuito electoral"""

sns.set(style = 'darkgrid')
df = pd.read_csv("/content/Comuna1.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="P03", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Promedio de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 1: Promedio de edades por circuito electoral')

df = pd.read_csv("/content/Comuna2.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="P03", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Promedio de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 2: Promedio de edades por circuito electoral')

df = pd.read_csv("/content/Comuna3.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="P03", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Promedio de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 3: Promedio de edades por circuito electoral')

df = pd.read_csv("/content/Comuna4.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="P03", kind="bar",color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Promedio de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 4: Promedio de edades por circuito electoral')

df = pd.read_csv("/content/Comuna5.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="P03", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Promedio de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 5: Promedio de edades por circuito electoral')

df = pd.read_csv("/content/Comuna6.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="P03", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Promedio de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 6: Promedio de edades por circuito electoral')

df = pd.read_csv("/content/Comuna7.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="P03", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Promedio de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 7: Promedio de edades por circuito electoral')

df = pd.read_csv("/content/Comuna8.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="P03", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Promedio de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 8: Promedio de edades por circuito electoral')

df = pd.read_csv("/content/Comuna9.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="P03", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Promedio de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 9: Promedio de edades por circuito electoral')

df = pd.read_csv("/content/Comuna10.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="P03", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Promedio de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 10: Promedio de edades por circuito electoral')

df = pd.read_csv("/content/Comuna11.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="P03", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Promedio de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 11: Promedio de edades por circuito electoral')

df = pd.read_csv("/content/Comuna12.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="P03", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Promedio de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 12: Promedio de edades por circuito electoral')

df = pd.read_csv("/content/Comuna13.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="P03", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Promedio de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 13: Promedio de edades por circuito electoral')

df = pd.read_csv("/content/Comuna14.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="P03", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Promedio de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 14: Promedio de edades por circuito electoral')

df = pd.read_csv("/content/Comuna15.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="P03", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Promedio de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 15: Promedio de edades por circuito electoral')

"""Mediana de edad por comuna

"""

df = pd.read_csv("/content/mediana_edad_comuna.csv")
sns.set(style = 'darkgrid')
eje_x = df["NOMBRE_REGION"]
eje_y = df["MEDIANA_EDAD"]
plt.bar(eje_x, eje_y, color="lightcoral")
plt.xticks(rotation=90)
plt.ylabel("Mediana de edad")
plt.title('Mediana de edad por comuna')
plt.ylim(30,48)
plt.show()

"""Mediana de edad por circuito electoral"""

df = pd.read_csv("/content/Mediana_Comuna1.csv")
sns.set(style = 'darkgrid')
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="MEDIANA_EDAD", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Mediana de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 1: Mediana de edades por circuito electoral')

df = pd.read_csv("/content/Mediana_Comuna2.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="MEDIANA_EDAD", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Mediana de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 2: Mediana de edades por circuito electoral')

df = pd.read_csv("/content/Mediana_Comuna3.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="MEDIANA_EDAD", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Mediana de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 3: Mediana de edades por circuito electoral')

df = pd.read_csv("/content/Mediana_Comuna4.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="MEDIANA_EDAD", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Mediana de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 4: Mediana de edades por circuito electoral')

df = pd.read_csv("/content/Mediana_Comuna5.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="MEDIANA_EDAD", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Mediana de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 5: Mediana de edades por circuito electoral')

df = pd.read_csv("/content/Mediana_Comuna6.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="MEDIANA_EDAD", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Mediana de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 6: Mediana de edades por circuito electoral')

df = pd.read_csv("/content/Mediana_Comuna7.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="MEDIANA_EDAD", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Mediana de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 7: Mediana de edades por circuito electoral')

df = pd.read_csv("/content/Mediana_Comuna8.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="MEDIANA_EDAD", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Mediana de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 8: Mediana de edades por circuito electoral')

df = pd.read_csv("/content/Mediana_Comuna9.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="MEDIANA_EDAD", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Mediana de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 9: Mediana de edades por circuito electoral')

df = pd.read_csv("/content/Mediana_Comuna10.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="MEDIANA_EDAD", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Mediana de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 10: Mediana de edades por circuito electoral')

df = pd.read_csv("/content/Mediana_Comuna11.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="MEDIANA_EDAD", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Mediana de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 11: Mediana de edades por circuito electoral')

df = pd.read_csv("/content/Mediana_Comuna12.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="MEDIANA_EDAD", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Mediana de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 12: Mediana de edades por circuito electoral')

df = pd.read_csv("/content/Mediana_Comuna13.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="MEDIANA_EDAD", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Mediana de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 13: Mediana de edades por circuito electoral')

df = pd.read_csv("/content/Mediana_Comuna14.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="MEDIANA_EDAD", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Mediana de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 14: Mediana de edades por circuito electoral')

df = pd.read_csv("/content/Mediana_Comuna15.csv")
fig2=sns.catplot(data=df, x="CODIGO_CIRCUITO", y="MEDIANA_EDAD", kind="bar", color="lightcoral")
fig2.set_xticklabels(df.CODIGO_CIRCUITO, rotation=90)
plt.ylabel("Mediana de edad")
plt.xlabel ("Circuitos")
plt.title('Comuna 15: Mediana de edades por circuito electoral')

df_1 = pd.read_csv("/content/promedio_edad_comuna_16_para_arriba.csv")
df_2 = pd.read_csv("/content/pres_FIT_comuna.csv")

PromedioEdad_PorcentajeFIT = pd.merge(df_1, df_2, on="NOMBRE_REGION")

PromedioEdad_PorcentajeFIT.to_csv("PromedioEdad_PorcentajeFIT.csv",
           index=False)

df =  pd.read_csv('PromedioEdad_PorcentajeFIT.csv')
labels = df["NOMBRE_REGION"]
fit = df["PORCENTAJE_AGRUPACION"]
edad = df["P03"]

x = np.arange(len(labels))  # the label locations
width = 0.35  # the width of the bars

fig, ax = plt.subplots()
rects1 = ax.bar(x - width/2, fit, width, label='Porcentaje de votos al FIT')
rects2 = ax.bar(x + width/2, edad, width, label='Promedio de edades')


ax.set_title('Comparación porcentaje de votos presidenciales de FIT y promedio de edades por comuna')
ax.set_xticks(x)
ax.set_xticklabels(labels)
ax.legend()

plt.xticks(rotation=90)

fig.tight_layout()

plt.show()

#Grafico votos presidenciales por comuna partido FIT
df =  pd.read_csv('pres_FIT_comuna.csv')
eje_x = df["NOMBRE_REGION"]
eje_y = df["PORCENTAJE_AGRUPACION"]
plt.bar(eje_x, eje_y)
plt.xticks(rotation=90)
plt.ylabel('Porcentajes a voto presidencial')
plt.xlabel('Comunas')
plt.title('Porcentaje de votos al FIT por comuna')
plt.show()

#Gráfico con promedio de edades por comuna (mayores a 16)
sns.set(style = 'darkgrid')
df = pd.read_csv("/content/promedio_edad_comuna_16_para_arriba.csv")
eje_x = df["NOMBRE_REGION"]
eje_y = df["P03"]
plt.bar(eje_x, eje_y, color="lightcoral")
plt.xticks(rotation=90)
plt.ylabel("Promedio de edad")
plt.title('Promedio de edad por comuna')
plt.show()